### ISSUE TITLE
fix the rust CI

### ISSUE THREAD

**Issue by keewis** [keewis/grid-indexing#8]
`cargo test` fails when building using `conda-forge`'s rust toolchain or when linking, causing the rust CI to fail on all platforms. Figure out how to fix that.

**Comment by keewis** [comment]
#10 didn't actually fix the CI, so we might instead have to use a rust setup action instead of installing from `conda-forge`:
```yaml
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
```
